-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   at:        2020-05-14 22:43:02 ICT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g

CREATE TABLE taikhoan (
    username  VARCHAR2(32),
    password  VARCHAR2(32)
);

CREATE TABLE lop (
    malop   VARCHAR2(10) NOT NULL,
    tenlop  NVARCHAR2(50)
);

ALTER TABLE lop ADD CONSTRAINT lop_pk PRIMARY KEY ( malop );
CREATE TABLE sinhvien (
    mssv               VARCHAR2(10) NOT NULL,
    hoten_sinhvien     NVARCHAR2(50),
    lop              VARCHAR2(10) NOT NULL,
    ngaysinh_sv  DATE,
    diachi_sv    NVARCHAR2(150),
    gioitinh_sv  NCHAR(3),
    cmnd_sv     VARCHAR2(11),
    sdt_sv     CHAR(10),
    email_sv     VARCHAR2(50)
);

ALTER TABLE sinhvien ADD CONSTRAINT sinhvien_pk PRIMARY KEY ( mssv );

CREATE TABLE giaovien (
    magiaovien         VARCHAR2(15) NOT NULL,
    hoten_giaovien     NVARCHAR2(50),
    ngaysinh_gv  DATE,
    diachi_gv    NVARCHAR2(150),
    gioitinh_gv  NCHAR(3),
    cmnd_gv      VARCHAR2(11),
    sdt_gv     CHAR(10),
    email_gv     VARCHAR2(50),
    mabomon            VARCHAR2(10),
    truongkhoa         CHAR(1),
    loaigiaovien       CHAR(1)
    
);

ALTER TABLE giaovien ADD CONSTRAINT giaovien_pk PRIMARY KEY ( magiaovien );

CREATE TABLE bomon (
    mabomon      VARCHAR2(10) NOT NULL,
    tenbomon     NVARCHAR2(50),
    truongbomon  VARCHAR2(15)
);

ALTER TABLE bomon ADD CONSTRAINT bomon_pk PRIMARY KEY ( mabomon );

CREATE TABLE monhoc (
    mamonhoc       VARCHAR2(10) NOT NULL,
    tenmonhoc      NVARCHAR2(50),
    mabomon  	   VARCHAR2(10),
    sotinchi       NUMBER
);

ALTER TABLE monhoc ADD CONSTRAINT monhoc_pk PRIMARY KEY ( mamonhoc );

CREATE TABLE thoikhoabieu (
    malop                VARCHAR2(10) NOT NULL,
    mamonhoc             VARCHAR2(10) NOT NULL,
    hocky                NUMBER NOT NULL,
    namhoc               CHAR(9) NOT NULL,
    phonghoc             VARCHAR2(10),
    giaoviengiangday  VARCHAR2(15),
    sosinhvientoida	 NUMBER
    
);

ALTER TABLE thoikhoabieu
    ADD CONSTRAINT thoikhoabieu_pk PRIMARY KEY ( hocky,
                                                 namhoc,
                                                 malop,
                                                 mamonhoc );

CREATE TABLE diem (
    mssv      VARCHAR2(10) NOT NULL,
    malop     VARCHAR2(10) NOT NULL,
    mamonhoc  VARCHAR2(10) NOT NULL,
    hocky     NUMBER(1) NOT NULL,
    namhoc    CHAR(9) NOT NULL,
    diemgiuaky    FLOAT,
    diemcuoiky    FLOAT,
    diemkhac  FLOAT,
    diemtong  FLOAT
);

ALTER TABLE diem
    ADD CONSTRAINT diem_pk PRIMARY KEY ( hocky,
                                         namhoc,
                                         malop,
                                         mamonhoc,
                                         mssv );

ALTER TABLE bomon
    ADD CONSTRAINT bomon_giaovien_fk FOREIGN KEY ( truongbomon )
        REFERENCES giaovien ( magiaovien );

ALTER TABLE diem
    ADD CONSTRAINT diem_sinhvien_fk FOREIGN KEY ( mssv )
        REFERENCES sinhvien ( mssv );

ALTER TABLE diem
    ADD CONSTRAINT diem_thoikhoabieu_fk FOREIGN KEY ( hocky,
                                                      namhoc,
                                                      malop,
                                                      mamonhoc )
        REFERENCES thoikhoabieu ( hocky,
                                  namhoc,
                                  malop,
                                  mamonhoc );

ALTER TABLE giaovien
    ADD CONSTRAINT giaovien_bomon_fk FOREIGN KEY ( mabomon )
        REFERENCES bomon ( mabomon );


ALTER TABLE monhoc
    ADD CONSTRAINT monhoc_bomon_fk FOREIGN KEY ( mabomon )
        REFERENCES bomon ( mabomon );

ALTER TABLE sinhvien
    ADD CONSTRAINT sinhvien_lop_fk FOREIGN KEY ( lop )
        REFERENCES lop ( malop );

ALTER TABLE thoikhoabieu
    ADD CONSTRAINT thoikhoabieu_giaovien_fk FOREIGN KEY ( giaoviengiangday )
        REFERENCES giaovien ( magiaovien );

ALTER TABLE thoikhoabieu
    ADD CONSTRAINT thoikhoabieu_lop_fk FOREIGN KEY ( malop )
        REFERENCES lop ( malop );

ALTER TABLE thoikhoabieu
    ADD CONSTRAINT thoikhoabieu_monhoc_fk FOREIGN KEY ( mamonhoc )
        REFERENCES monhoc ( mamonhoc );

----Tao user sinhvien, giaovu, giaovien

--User : SinhVien
create user sv1 identified by sv1
        default tablespace users
        TEMPORARY TABLESPACE temp
        Quota 10M on users;
grant create session to sv1;

create user sv2 identified by sv2
        default tablespace users
        TEMPORARY TABLESPACE temp
        Quota 10M on users;
grant create session to sv2;
--User: GiaoVu

create user giaovu identified by giaovu
        default tablespace users
        TEMPORARY TABLESPACE temp
        Quota 10M on users;
grant create session to giaovu;

--User: GiaoVien
create user gvktpm_lbuan identified by lbluan
        default tablespace users
        TEMPORARY TABLESPACE temp
        Quota 10M on users;
grant create session to gvktpm_lbuan;

create user gvhttt_nahoang identified by nahoang
        default tablespace users
        TEMPORARY TABLESPACE temp
        Quota 10M on users;
grant create session to gvhttt_nahoang;

create user gvkhmt_ltlinh identified by ltlinh
        default tablespace users
        TEMPORARY TABLESPACE temp
        Quota 10M on users;
grant create session to gvkhmt_ltlinh; 

-----
---Cap quyen select bang giaovien cho giao vien
grant select on sec_admin.giaovien to giaovu;
grant select on sec_admin.giaovien to gvktpm_lbuan;
