CREATE OR REPLACE FUNCTION ENCRYPT_(INPUT_DATA IN VARCHAR2)
    RETURN RAW DETERMINISTIC
IS
    MY_KEY VARCHAR2(100) := 'AHIHI';
    ENCRYPTION_TYPE PLS_INTEGER := DBMS_CRYPTO.ENCRYPT_DES
                                    + DBMS_CRYPTO.CHAIN_ECB
                                    + DBMS_CRYPTO.PAD_PKCS5;
    ENCRYPTED_DATA RAW(3000);
BEGIN
    ENCRYPTED_DATA := DBMS_CRYPTO.ENCRYPT(
        SRC => UTL_RAW.CAST_TO_RAW(INPUT_DATA),
        TYP => ENCRYPTION_TYPE,
        KEY => UTL_I18N.STRING_TO_RAW(MY_KEY, 'AL32UTF8')
    );
    RETURN ENCRYPTED_DATA;
END ENCRYPT_;
/

CREATE OR REPLACE FUNCTION DECRYPT_(INPUT_DATA IN RAW)
    RETURN VARCHAR2 DETERMINISTIC
IS
    MY_KEY VARCHAR2(100) := 'AHIHI';
    DECRYPTION_TYPE PLS_INTEGER := DBMS_CRYPTO.ENCRYPT_DES
                                    + DBMS_CRYPTO.CHAIN_ECB
                                    + DBMS_CRYPTO.PAD_PKCS5;
    DECRYPTED_DATA RAW(3000);
BEGIN
    DECRYPTED_DATA := dbms_crypto.decrypt(
        SRC => INPUT_DATA,
        TYP => DECRYPTION_TYPE,
        KEY => UTL_I18N.STRING_TO_RAW(MY_KEY, 'AL32UTF8')
    );
    RETURN UTL_RAW.CAST_TO_VARCHAR2(DECRYPTED_DATA);
END DECRYPT_;
/
--ENCRYPT WORKING WELL
BEGIN 
    FOR STT IN(SELECT COUNT(MSSV)FROM SINHVIEN)
    LOOP
        UPDATE SINHVIEN SET HOTENSINHVIEN = ENCRYPT_(HOTENSINHVIEN);
    END LOOP;
END;
--DECRYPT NOT WORKING, ERROR CODE ORA-06512: at "SYS.DBMS_CRYPTO_FFI", line 67
BEGIN 
    FOR STT IN(SELECT COUNT(MSSV)FROM SINHVIEN)
    LOOP
        UPDATE SINHVIEN SET HOTENSINHVIEN = DECRYPT_(HOTENSINHVIEN);
    END LOOP;
END;
--TEST DATA ENCRYPTED
SELECT * FROM SINHVIEN;

SELECT MSSV, DECRYPT_(HOTENSINHVIEN), DTB FROM SINHVIEN;

--HASH MD5 with objuscation toolkit
CREATE OR REPLACE FUNCTION hash_key (v_input VARCHAR2)
   RETURN dbms_obfuscation_toolkit.varchar2_checksum
AS
BEGIN
   RETURN dbms_obfuscation_toolkit.md5(input_string => v_input);
END hash_key;
/
SELECT MSSV, hash_key(HOTENSINHVIEN), DTB FROM SINHVIEN;

--RESTORE DATABASE SAMPLE
DROP TABLE SINHVIEN;
/
CREATE TABLE SINHVIEN(
    MSSV NUMBER(*,0),
    HOTENSINHVIEN VARCHAR2(100),
    DTB NUMBER(*,0)
);
/
INSERT INTO SINHVIEN(MSSV, HOTENSINHVIEN, DTB) VALUES(1, 'NGUYEN A', 10);
INSERT INTO SINHVIEN(MSSV, HOTENSINHVIEN, DTB) VALUES(2, 'NGUYEN B', 9);
INSERT INTO SINHVIEN(MSSV, HOTENSINHVIEN, DTB) VALUES(3, 'NGUYEN C', 8);
INSERT INTO SINHVIEN(MSSV, HOTENSINHVIEN, DTB) VALUES(4, 'NGUYEN D', 7);
INSERT INTO SINHVIEN(MSSV, HOTENSINHVIEN, DTB) VALUES(5, 'NGUYEN E', 6);
/